/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SurfaceRouteImport } from './routes/surface'
import { Route as RefineryRouteImport } from './routes/refinery'
import { Route as CoreRouteImport } from './routes/core'
import { Route as IndexRouteImport } from './routes/index'

const SurfaceRoute = SurfaceRouteImport.update({
  id: '/surface',
  path: '/surface',
  getParentRoute: () => rootRouteImport,
} as any)
const RefineryRoute = RefineryRouteImport.update({
  id: '/refinery',
  path: '/refinery',
  getParentRoute: () => rootRouteImport,
} as any)
const CoreRoute = CoreRouteImport.update({
  id: '/core',
  path: '/core',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/core': typeof CoreRoute
  '/refinery': typeof RefineryRoute
  '/surface': typeof SurfaceRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/core': typeof CoreRoute
  '/refinery': typeof RefineryRoute
  '/surface': typeof SurfaceRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/core': typeof CoreRoute
  '/refinery': typeof RefineryRoute
  '/surface': typeof SurfaceRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/core' | '/refinery' | '/surface'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/core' | '/refinery' | '/surface'
  id: '__root__' | '/' | '/core' | '/refinery' | '/surface'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CoreRoute: typeof CoreRoute
  RefineryRoute: typeof RefineryRoute
  SurfaceRoute: typeof SurfaceRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/surface': {
      id: '/surface'
      path: '/surface'
      fullPath: '/surface'
      preLoaderRoute: typeof SurfaceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/refinery': {
      id: '/refinery'
      path: '/refinery'
      fullPath: '/refinery'
      preLoaderRoute: typeof RefineryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/core': {
      id: '/core'
      path: '/core'
      fullPath: '/core'
      preLoaderRoute: typeof CoreRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CoreRoute: CoreRoute,
  RefineryRoute: RefineryRoute,
  SurfaceRoute: SurfaceRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
